# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         IO-Capture-Extended
version:      0.11
version_from: lib/IO/Capture/Extended.pm
installdirs:  site
requires:
    IO::Capture:                   0.05
    Test::Simple:                  0.44

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.30
