---
abstract: 'Extend functionality of IO::Capture'
author:
  - 'James E Keenan (jkeenan@cpan.org)'
build_requires:
  ExtUtils::MakeMaker: 0
configure_requires:
  ExtUtils::MakeMaker: 0
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 6.92, CPAN::Meta::Converter version 2.120921'
license: unknown
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: IO-Capture-Extended
no_index:
  directory:
    - t
    - inc
requires:
  IO::Capture: 0.05
  Test::Simple: 0.44
version: 0.12
